name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

defaults:
  run:
    shell: cmd

jobs:
  deploy_dev:
    runs-on: [self-hosted, pc, dev]
    env:
      PM2_HOME: C:\Users\Ebram\.pm2 # نفس بيت PM2 بتاع المستخدم
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci --omit=dev

      - name: Start / Restart with PM2
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"
          npx --yes pm2 kill || ver >NUL
          npx --yes pm2 delete demo-ci || ver >NUL
          npx --yes pm2 start "%CD%\index.js" --name demo-ci --time ^
            -o "%PM2_HOME%\logs\demo-ci-out.log" ^
            -e "%PM2_HOME%\logs\demo-ci-error.log"
          npx --yes pm2 save
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci

      - name: Health check
        run: |
          set OK=1
          for /L %%i in (1,1,20) do (
            echo [%%i/20] GET /hello
            curl -s http://localhost:3000/hello >NUL && set OK=0 && goto H1
            timeout /t 2 /nobreak >NUL
          )
          :H1
          if %OK% NEQ 0 exit /b 1

          set OK=1
          for /L %%i in (1,1,20) do (
            echo [%%i/20] GET /bye
            curl -s http://localhost:3000/bye >NUL && set OK=0 && goto H2
            timeout /t 2 /nobreak >NUL
          )
          :H2
          if %OK% NEQ 0 exit /b 1

      - name: PM2 logs on failure
        if: failure()
        run: |
          echo ===== PM2 LIST =====
          npx --yes pm2 list
          echo ===== DESCRIBE =====
          npx --yes pm2 describe demo-ci || echo (no describe)
          echo ===== ERROR LOG =====
          type "%PM2_HOME%\logs\demo-ci-error.log" 2>NUL || echo (no error log)
          echo ===== OUT LOG =====
          type "%PM2_HOME%\logs\demo-ci-out.log"  2>NUL || echo (no out log)
