name: CI/CD

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch: {}

defaults:
  run:
    shell: cmd # شغّل كل أوامر run بــ CMD على ويندوز

jobs:
  deploy_dev:
    runs-on: [self-hosted, pc, dev]
    # متغيرات PM2 لكل خطوات الجوب
    env:
      PM2_HOME: C:\pm2\dev
      PM2_RPC_PORT: \\.\pipe\pm2-${{ github.run_id }}-rpc
      PM2_PUB_PORT: \\.\pipe\pm2-${{ github.run_id }}-pub
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Prepare PM2 home
        run: if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"

      - name: Install dependencies
        run: npm ci --omit=dev

        # شغّل/ابدأ من جديد باسم demo-ci
      - name: PM2 start/restart (dev)
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          node -v
          call node -e "require('express'); console.log('express OK')"
          call node -e "require('fs').accessSync('./index.js'); console.log('index file OK')"
          npx --yes pm2 -v
          npx --yes pm2 delete demo-ci || ver >NUL
          npx --yes pm2 start "%GITHUB_WORKSPACE%\index.js" --name demo-ci --time
          npx --yes pm2 save
          rem شوف اللي شغّال فورًا بنفس الـ env
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci

      - name: Health check (dev)
        shell: powershell
        run: |
          $urls = @("http://localhost:3000/hello","http://localhost:3000/bye")
          foreach ($u in $urls) {
            $ok = $false
            foreach ($i in 1..15) {
              try {
                Invoke-WebRequest $u -UseBasicParsing -TimeoutSec 3 | Out-Null
                $ok = $true; break
              } catch { Start-Sleep -Seconds 2 }
            }
            if (-not $ok) { throw "Health check failed: $u" }
          }

      - name: PM2 debug (only if failed)
        if: failure()
        run: |
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci || echo (no describe)
          echo ===== logs dir =====
          dir "%PM2_HOME%\logs"
          echo ===== error log =====
          type "%PM2_HOME%\logs\demo-ci-error.log" 2> NUL || echo (no error log)
          echo ===== out log =====
          type "%PM2_HOME%\logs\demo-ci-out.log"  2> NUL || echo (no out log)

  deploy_prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, lab, prod]
    environment: { name: production }
    env:
      PM2_HOME: C:\pm2\prod
      PM2_RPC_PORT: \\.\pipe\pm2-${{ github.run_id }}-rpc
      PM2_PUB_PORT: \\.\pipe\pm2-${{ github.run_id }}-pub
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Prepare PM2 home
        run: if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: PM2 start/restart (prod)
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          npx --yes pm2 delete demo-ci || ver >NUL
          npx --yes pm2 start "%GITHUB_WORKSPACE%\index.js" --name demo-ci --time
          npx --yes pm2 save
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci

      - name: Health check (prod)
        shell: powershell
        run: |
          $urls = @("http://localhost:3000/hello","http://localhost:3000/bye")
          foreach ($u in $urls) {
            $ok = $false
            foreach ($i in 1..15) {
              try {
                Invoke-WebRequest $u -UseBasicParsing -TimeoutSec 3 | Out-Null
                $ok = $true; break
              } catch { Start-Sleep -Seconds 2 }
            }
            if (-not $ok) { throw "Health check failed: $u" }
          }

      - name: PM2 debug (only if failed)
        if: failure()
        run: |
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci || echo (no describe)
          dir "%PM2_HOME%\logs"
          type "%PM2_HOME%\logs\demo-ci-error.log" 2> NUL || echo (no error log)
          type "%PM2_HOME%\logs\demo-ci-out.log"  2> NUL || echo (no out log)
