name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

defaults:
  run:
    shell: cmd

jobs:
  deploy_dev:
    runs-on: [self-hosted, pc, dev]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --omit=dev

      - name: Setup PM2 environment
              run: |
                setx HOMEPATH "%USERPROFILE%"
                setx HOMEDRIVE "%SystemDrive%"
                setx PM2_HOME "%USERPROFILE%\.pm2"
                mkdir "%USERPROFILE%\.pm2" 2>nul || echo "PM2 directory already exists"
                
      - name: PM2 clean start
        run: |
          echo "Starting PM2 with ecosystem.config.js..."
          echo "Current directory: %CD%"
          pm2 ls
          ls -la
          echo CWD=%CD%
