name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

defaults:
  run:
    shell: cmd

jobs:
  deploy_dev:
    runs-on: [self-hosted, pc, dev]
    env:
      PM2_HOME: C:\pm2\dev
      PM2_RPC_PORT: \\.\pipe\pm2-${{ github.run_id }}-rpc
      PM2_PUB_PORT: \\.\pipe\pm2-${{ github.run_id }}-pub

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Prepare PM2 home
        run: if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"

      - name: Install dependencies
        run: npm ci --omit=dev

      # شغّل/أعد تشغيل السيرفر مباشرة من index.js (من غير ecosystem مؤقتًا)
      - name: PM2 start/restart (dev)
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          echo CWD=%CD%
          echo PM2_HOME=%PM2_HOME%
          node -v
          call node -e "require('express'); console.log('express OK')"
          call node -e "require('fs').accessSync('./index.js'); console.log('index file OK')"
          npx --yes pm2 -v
          npx --yes pm2 restart demo-ci || npx --yes pm2 start "%GITHUB_WORKSPACE%\index.js" --name demo-ci --time
          npx --yes pm2 save
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci

      # الهيلث تشيك بـ PowerShell (من غير goto)
      - name: Health check (dev)
        shell: powershell
        run: |
          $urls = @("http://localhost:3000/hello","http://localhost:3000/bye")
          foreach ($u in $urls) {
            $ok = $false
            foreach ($i in 1..15) {
              try {
                Invoke-WebRequest $u -UseBasicParsing -TimeoutSec 3 | Out-Null
                $ok = $true; break
              } catch { Start-Sleep -Seconds 2 }
            }
            if (-not $ok) { throw "Health check failed: $u" }
          }

      - name: PM2 debug (only if failed)
        if: failure()
        run: |
          npx --yes pm2 list
          npx --yes pm2 describe demo-ci || echo (no describe)
          echo ===== logs dir =====
          dir "%PM2_HOME%\logs"
          echo ===== error log =====
          type "%PM2_HOME%\logs\demo-ci-error.log" 2> NUL || echo (no error log)
          echo ===== out log =====
          type "%PM2_HOME%\logs\demo-ci-out.log"  2> NUL || echo (no out log)
