name: CI/CD

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  deploy_dev:
    runs-on: [self-hosted, pc, dev]
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }

      - run: npm ci --omit=dev

      - name: Setup PM2 Home
        run: |
          # استخدام مسار ثابت خارج workspace
          PM2_HOME="/etc/pm2"
          echo "PM2_HOME=${PM2_HOME}" >> $GITHUB_ENV
          sudo mkdir -p ${PM2_HOME}
          sudo chown -R $USER:${PM2_HOME}

      - name: PM2 deploy (dev)
        run: |
          cd "$GITHUB_WORKSPACE"
          # إيقاف التطبيق إذا كان يعمل
          npx pm2 delete ecosystem.config.js || true
          # بدء التطبيق مع البيئة الصحيحة
          npx pm2 start ecosystem.config.js --env development
          # حفظ قائمة العمليات
          npx pm2 save
          # إنشاء سكريبت بدء تلقائي
          npx pm2 startup | tail -n 1 | bash
          # حفظ القائمة النهائية
          npx pm2 save

      - name: PM2 debug (dev)
        if: always()
        run: |
          npx pm2 list
          npx pm2 describe demo-ci || true
          echo "===== logs ====="
          npx pm2 logs demo-ci --lines 20 || true

      - name: Health check (dev)
        run: |
          curl -sSf http://localhost:3000/hello
          curl -sSf http://localhost:3000/bye

  deploy_prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, lab, prod]
    environment: { name: production }
    defaults: { run: { shell: bash } }  # توحيد استخدام bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }

      - run: npm ci --omit=dev

      - name: Setup PM2 Home
        run: |
          PM2_HOME="/etc/pm2"
          echo "PM2_HOME=${PM2_HOME}" >> $GITHUB_ENV
          sudo mkdir -p ${PM2_HOME}
          sudo chown -R $USER:${PM2_HOME}

      - name: PM2 deploy (prod)
        run: |
          cd "$GITHUB_WORKSPACE"
          # استخدام ecosystem.config.js بدلاً من index.js مباشرة
          npx pm2 delete ecosystem.config.js || true
          npx pm2 start ecosystem.config.js --env production
          npx pm2 save
          npx pm2 startup | tail -n 1 | bash
          npx pm2 save

      - name: PM2 debug (prod)
        if: always()
        run: |
          npx pm2 list
          npx pm2 describe demo-ci || true
          npx pm2 logs demo-ci --lines 20 || true

      - name: Health check (prod)
        run: |
          curl -sSf http://localhost:3000/hello
          curl -sSf http://localhost:3000/bye