name: CI/CD

on:
  push:
    branches: ["main"] # أي push على main = CI + Deploy Dev
    tags: ["v*"] # أي tag يبدأ بـ v = Deploy Prod
  workflow_dispatch: {}

jobs:
  # --- CI على سحابة GitHub ---
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm test

  # --- Deploy Dev على جهاز PC ---
  deploy_dev:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, pc, dev]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci --omit=dev

      - name: PM2 deploy (dev)
        run: |
          set PM2_HOME=%GITHUB_WORKSPACE%\.pm2
          if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"
          pm2 --version
          pm2 delete all
          pm2 start ecosystem.config.js --env development
          pm2 save

      - name: Health check (dev)
        run: |
          curl -sSf http://localhost:3000/hello >NUL

  # --- Deploy Prod على جهاز Lab (Tag فقط) ---
  deploy_prod:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, lab, prod]
    environment:
      name: production
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci --omit=dev

      - name: PM2 deploy (prod)
        run: |
          set PM2_HOME=%GITHUB_WORKSPACE%\.pm2
          if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"
          npx --yes pm2 --version
          npx --yes pm2 kill || ver >NUL
          npx --yes pm2 startOrReload ecosystem.config.js --env production
          npx --yes pm2 save

      - name: Health check (prod)
        run: |
          curl -sSf http://localhost:3000/hello >NUL
