name: CI/CD (dev only, no PM2)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

defaults:
  run:
    shell: cmd

jobs:
  dev_quick_run:
    runs-on: [self-hosted, pc, dev]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps (prod only)
        run: npm ci --omit=dev

      - name: Start app (node index.js, background)
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          echo CWD=%CD%
          rem شغّل Node في الخلفية وسجّل الـ PID + اللوجز
          powershell -NoProfile -ExecutionPolicy Bypass -Command ^
            "$env:PORT=3000; " ^
            "$p = Start-Process node 'index.js' -PassThru -RedirectStandardOutput 'out.log' -RedirectStandardError 'err.log' -WorkingDirectory $env:GITHUB_WORKSPACE; " ^
            "$p.Id | Out-File 'server.pid' -Encoding ascii; " ^
            "Write-Host ('Started PID: ' + $p.Id)"

      - name: Health check
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -Command ^
            "$urls=@('http://localhost:3000/hello','http://localhost:3000/bye');" ^
            "foreach($u in $urls){" ^
            "  $ok=$false; foreach($i in 1..20){try{Invoke-WebRequest -UseBasicParsing -TimeoutSec 3 $u|Out-Null; $ok=$true; break} catch{Start-Sleep -s 2}}" ^
            "  if(-not $ok){ throw \"Health check failed: $u\" }" ^
            "}"

      - name: Stop app & show logs
        if: always()
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          powershell -NoProfile -ExecutionPolicy Bypass -Command ^
            "if (Test-Path 'server.pid'){ $pid=[int](Get-Content 'server.pid'); Write-Host ('Stopping PID: ' + $pid); try{ Stop-Process -Id $pid -Force } catch{}; Start-Sleep -s 1 }"
          echo ===== err.log =====
          type err.log 2>NUL || echo (no err.log)
          echo ===== out.log =====
          type out.log 2>NUL || echo (no out.log)
